nginx:
  build: ./nginx/
  ports:
   - "80:80"
   - "443:443"
  links:
   - titter
   - login
   - storage
   - webgold

mongo:
  image: mongo:latest
  ports:
  - "27017:27017"


login:
  build: ./Login-WRIO-App/
  ports:
   - "5000:5000"
  volumes:
   - ./Login-WRIO-App/:/srv/www/
  extra_hosts:
   - "titter.wrioos.local:10.211.55.3"
   - "storage.wrioos.local:10.211.55.3"
   - "webgold.wrioos.local:10.211.55.3"


titter:
  build: ./Titter-WRIO-App/
  ports:
   - "5001:5001"
  volumes:
   - ./Titter-WRIO-App/:/srv/www/
  links:
   - rabbitmq
  extra_hosts:
    - "titter.wrioos.local:10.211.55.3"
    - "login.wrioos.local:10.211.55.3"
    - "webgold.wrioos.local:10.211.55.3"

storage:
  build: ./Storage-WRIO-App/
  ports:
   - "5002:5002"
  volumes:
   - ./Storage-WRIO-App/:/srv/www/
   - ./hub/:/hub
  extra_hosts:
    - "titter.wrioos.local:10.211.55.3"
    - "login.wrioos.local:10.211.55.3"
  #command: sh -c "cd /srv/www && node server.js"  # DEVMODE off, comment this to activate dev mode

webgold:
  build: ./webGold-WRIO-App/
  links:
   - mongo
#   - testrpc
   - rabbitmq
  ports:
   - "5003:5003"
  volumes:
   - ./webGold-WRIO-App/:/srv/www/
  command: sh -c "cd /srv/www && node server.js" # DEVMODE off,comment this to activate dev mode

#chess:
#  build: ./Chess-WRIO-Game/
#  ports:
#   - "5005:5005"
#  volumes:
#   - ./Chess-WRIO-Game/:/srv/www/
#  links:
#    - titter

rabbitmq:
  image: "rabbitmq"
  ports:
    - "15672:15672"
    - "5672:5672"
